name: cook_book
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite:
  path:

  simple_animations: ^1.3.3

  http: ^0.13.5
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  form_field_validator: ^1.1.0


flutter:

  uses-material-design: true

  assets:
    - image/

